[tools]

go = '1.25.5'
node = '24.12.0'
python = '3.14.2'
perl = '5.42.0'
rust = "1.92.0"
ruby = "4.0.0"
php = "8.5.1"
# gradle が問題起こしがちなので最新の LTS をつかうこと
java = "25.0.1"
vim = "9.1.1825"
watchexec = "2.3.2"
bun = "1.3.5"
terraform = "1.14.3"

[settings]
idiomatic_version_file_enable_tools = ["python"]

