[tools]

go = '1.25.5'
node = '24.12.0'
python = '3.14.2'
perl = '5.42.0'
rust = "1.92.0"
ruby = "4.0.0"
# https://github.com/asdf-community/asdf-php?tab=readme-ov-file#macos
# brew install gmp libsodium imagemagick
php = "8.3.17"
# gradle が問題起こしがちなので最新の LTS をつかうこと
java = "25.0.1"
vim = "9.1.1825"
watchexec = "2.3.2"
bun = "1.3.5"
terraform = "1.14.3"
"github:anomalyco/opencode" = "latest"
dotenvx = "1.51.4"

[settings]
idiomatic_version_file_enable_tools = ["python"]

